version: "3.9"

services:
  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      DB_HOST: postgres
      POSTGRES_PASSWORD: b4f7d02b4a5dcc14672e73d7e5ddd4c3
      POSTGRES_DATABASE: unicred
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
  app: 
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    ports:
      - 3302:3302
    depends_on:
      - postgres
    environment:
      - DATABASE_URL="postgresql://postgres:b4f7d02b4a5dcc14672e73d7e5ddd4c3@postgres:5432/unicred?schema=public"
    entrypoint: ["/usr/bin/dumb-init", "--", "./utils/wait-for-it.sh", "postgres:5432", "--"]
    command: npm start:dev
    restart: on-failure
    links:
      - postgres


  
volumes:
  postgres:
    driver: local